services:
  - name: frontend
    type: static_site
    repo: https://github.com/adanjelle/wildlife
    branch: main
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-backend-service.onrender.com

  - name: backend
    type: web
    repo: https://github.com/adanjelle/Backend
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
